The Great Ammo Purge
FortunaSS13/Fortuna pull request #250
Opened 2021-09-26 19:36 UTC by Tron-117

Comments out most ammo types except FMJ.

## About The Pull Request
This is for the eventual gun rework, in which damage is based on the gun itself rather than it's ammo type. The option to make the special ammos have been removed from the ammo bench, and can not even be spawned in via admin means. Some ammo types, like explosive ammo and the ricochet 45 ammo have been kept in, as well as the ammo that's used by raider mobs, which is fine as it's impossible to make those anyway.

## Why It's Good For The Game
Makes balance a heellll of a lot easier.

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Commented out near every ammo type except FMJ.
/:cl:

2021-09-26 19:50 UTC, Tron-117 commented
Who is the ASS who scattered AP casings about the map aaaaahhhh.

2021-09-26 20:40 UTC, Looreydev commented on code/_globalvars/lists/maintenance_loot.dm
> +	///datum/design/ammolathe/a22plink
```suggestion
	
```

2021-09-26 20:40 UTC, Looreydev commented on code/datums/components/storage/concrete/pockets.dm
> +	*/
```suggestion
```

2021-09-26 20:40 UTC, Looreydev commented on code/game/objects/items/storage/belt.dm
> +		*/
```suggestion
```

2021-09-26 20:40 UTC, Looreydev commented on code/modules/jobs/job_types/wasteland.dm
> +							/obj/item/ammo_box/m44box=2
```suggestion
```

2021-09-26 20:42 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/pistol.dm
> +/*/obj/item/ammo_casing/c10mm/ap
Remove this whole commented block too.

2021-09-26 20:42 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/pistol.dm
> +/*/obj/item/ammo_casing/c9mm/ap
This too, slash it. (Line 26 to 40)

2021-09-26 20:42 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/pistol.dm
> +*/
```suggestion
```

2021-09-26 20:43 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/pistol.dm
> +/*/obj/item/ammo_casing/a22/hp
Delete this too. (Line 62 to 71)

2021-09-26 20:43 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/revolver.dm
> +*/
```suggestion
```

2021-09-26 20:43 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/revolver.dm
> +/*/obj/item/ammo_casing/m44/jhp
This block too. (Line 31 to 40)

2021-09-26 20:44 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/revolver.dm
> +/*/obj/item/ammo_casing/c4570/jhp
This. (Line 49 to 58)

2021-09-26 20:44 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/rifle.dm
> +/*/obj/item/ammo_casing/a762/ap
This. (Line 14 to 25)

2021-09-26 20:44 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/rifle.dm
> +/*/obj/item/ammo_casing/a556/jhp
This. (Line 34 to 45)

2021-09-26 20:45 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/smg.dm
> +/*/obj/item/ammo_casing/c45/jhp
This. (Line 9 to 18)

2021-09-26 20:45 UTC, Looreydev commented on code/modules/projectiles/ammunition/ballistic/sniper.dm
> +*/
```suggestion
```

2021-09-26 20:45 UTC, Looreydev commented on code/modules/projectiles/ammunition/caseless/_caseless.dm
> +/*/obj/item/ammo_casing/caseless/needle/ap
This. (Line 32 to 44)

2021-09-26 20:45 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/m22/plinking
This. (Line 68 to 77)

2021-09-26 20:45 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/c9mm/ap
This (Line 91 to 105)

2021-09-26 20:46 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +*/
```suggestion
```

2021-09-26 20:46 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +*/
```suggestion
```

2021-09-26 20:46 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/a357box/jhp
This (Line 174 to 183)

2021-09-26 20:46 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/m44box/jhp
This. (Line 198 to 207)

2021-09-26 20:47 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/c45/jhp
This. (Line 239 to 248)

2021-09-26 20:47 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/c4570box/jhp
This. (Line 271 to 280)

2021-09-26 20:47 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/a556/jhp
This. (Line 295 to 309)

2021-09-26 20:48 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/a762box/jhp
This. (Line 348 to 362)

2021-09-26 20:48 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +*/
```suggestion
```

2021-09-26 20:48 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/ammo_boxes.dm
> +/*/obj/item/ammo_box/needleap
This. (Line 694 to 711)

2021-09-26 20:48 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/external/pistol.dm
> +*/
```suggestion
```

2021-09-26 20:48 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/external/pistol.dm
> +*/
```suggestion
```

2021-09-26 20:49 UTC, Looreydev commented on code/modules/projectiles/boxes_magazines/external/rifle.dm
> +*/
```suggestion
```

2021-09-26 20:49 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/c22/hp
This. (Line 29 to 41)

2021-09-26 20:49 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/c9mm/ap
This. (Line 65 to 78)

2021-09-26 20:49 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +
```suggestion
```

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/c10mm/ap
This. (Line 101 to 114)

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +*/
```suggestion
```

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/a357/jhp
This. (Line 153 to 166)

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/m44/jhp
This. (Line 180 to 193)

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/c4570/jhp
This. (Line 211 to 224)

2021-09-26 20:50 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +*/
```suggestion
```

2021-09-26 20:51 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +/*/obj/item/projectile/bullet/needle/ap
This. (Line 287 to 300)

2021-09-26 20:51 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/rifle.dm
> +/*/obj/item/projectile/bullet/a556/ap
This. (Line 30 to 43)

2021-09-26 20:51 UTC, Looreydev commented on code/modules/projectiles/projectile/bullets/rifle.dm
> +/*/obj/item/projectile/bullet/a762/ap
This. (Line 78 to 97)

2021-09-26 20:51 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +/*/datum/design/ammolathe/c10mmjhp
This. (Line 228 to 241)

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:52 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +
```suggestion
```

2021-09-26 20:52 UTC, Tron-117 commented
Please stop you're flooding my email, I'll delete instead of comment out god damn

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:53 UTC, Tron-117 commented
PLEASE I GET IT AAGHH

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:53 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +*/
```suggestion
```

2021-09-26 20:54 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +/*/datum/design/ammolathe/a357jfp
This. (Line 495 to 515)

2021-09-26 20:54 UTC, Looreydev commented on code/modules/research/designs/ammolathe_designs.dm
> +/*/datum/design/ammolathe/a4570swc
This. (Line 599 to 619)

2021-09-26 20:55 UTC, Looreydev requested changes
Tl;dr - Remove the comments, delete the things entirely. The chance they will sit there and rot, and be messy is too high. Another point - we are using git, a version control system, which makes it super easy to to revert back to a point and just bring back changes / deleted files thanks to its history.

2021-09-27 16:04 UTC, Tron-117 commented
This PR is good to merge, but it'll merge with Adam's gun rework and my Armor Rework PR at the same time.

2021-09-29 04:17 UTC, Looreydev approved these changes

2021-09-30 05:15 UTC, AdamElTablawy commented
this is mergeable assuming it's updated

2021-10-05 22:08 UTC, merged