webedit stimpaks into freezers and vr workbenches
FortunaSS13/Fortuna pull request #269
Opened 2021-09-30 19:26 UTC by buffyuwu

:cl:
tweak: you can now store stimpaks in chemical storage fridges like any other medicine
fix: you can now put materials into the VR workbenches and lathes
/:cl:

2021-09-30 21:14 UTC, printer16 commented on code/modules/shuttle/on_move.dm
> +				M.adjustBruteLoss(120)
undocumented change

2021-09-30 21:38 UTC, hecksadecimal requested changes
Use the PR template.

2021-10-01 23:02 UTC, Looreydev requested changes
Please use the Pull Request Template, the full one.

2021-10-02 16:42 UTC, hecksadecimal submitted a review, later dismissed

2021-10-02 19:30 UTC, Looreydev requested changes

2021-10-02 19:30 UTC, Looreydev commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
>  					// /obj/item/reagent_containers/medigel,
```suggestion
```

2021-10-02 19:30 UTC, Looreydev commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
>  					// /obj/item/reagent_containers/medigel,
While you're at editing the file, be so nice and remove that comment.

2021-10-02 23:24 UTC, Looreydev approved these changes

2021-10-02 23:59 UTC, merged