pretty water
FortunaSS13/Fortuna pull request #270
Opened 2021-09-30 21:20 UTC by buffyuwu

🆑 
add: adds animated water effects when entering water
/:cl:

2021-09-30 21:37 UTC, hecksadecimal requested changes
Use the PR template.

2021-10-01 21:23 UTC, ThyBaron requested changes
Please remove the availability of kitten ears! For reasons I won't explain in great detail, implementing kitten ears will give the wrong effect, and is not helpful for our atmospheric progress thus far.

2021-10-01 21:23 UTC, ThyBaron commented on code/modules/vending/autodrobe.dm
> +						/obj/item/clothing/head/kitty = 1,
No.

2021-10-01 23:01 UTC, Looreydev requested changes
Use the full Pull Request Template as it is. This is simply a Standard that should be enforced.

2021-10-02 16:37 UTC, hecksadecimal approved these changes

2021-10-05 03:49 UTC, merged