Buffs salvaged PA move speed slightly, nerfs NCR PA, removes raider/hotrod PA.
FortunaSS13/Fortuna pull request #3
Opened 2021-08-15 00:58 UTC by Mannybrado

## About The Pull Request
title

## Why It's Good For The Game
makes salvaged PA more specialized without being stupidly inconsistent between versions. also, raider/hotrod PA are ugly.

## Changelog
:cl:
changelogs dont work
/:cl:

2021-08-15 11:29 UTC, panzer1944 commented
ok but why remove hotrod and raider.
I can understand them becoming craft-only, but straight up removing them fully is hghbhhghhh, especially when the reasoning is just `ugly` - just keep their values somewhat consistent, maybe make hotrod a bit faster at the cost of protection, and have raider just be a reskin, idk

2021-08-15 13:29 UTC, Wirpy commented
Don't remove hotrod/raider PA, they're pretty cool.

2021-08-15 14:52 UTC, Looreydev requested changes

2021-08-15 14:52 UTC, Looreydev commented on code/_globalvars/lists/maintenance_loot.dm
>  	/obj/item/clothing/head/helmet/f13/combat/mk2,
```suggestion
	/obj/item/clothing/head/helmet/f13/combat/mk2
```
Remove the comma

2021-08-15 14:52 UTC, Looreydev commented on code/game/objects/effects/spawners/f13lootdrop.dm
>  				/obj/effect/spawner/bundle/f13/armor/combat/mk2/dark,
```suggestion
				/obj/effect/spawner/bundle/f13/armor/combat/mk2/dark
```
Same here, remove comma

2021-08-15 14:52 UTC, Looreydev commented on code/modules/fallout/misc/gangs.dm
>  		/datum/gang_item/weapon/type93,
```suggestion
		/datum/gang_item/weapon/type93
```
Remove this comma too

2021-08-16 02:32 UTC, Mannybrado commented on code/game/objects/effects/spawners/f13lootdrop.dm
>  				/obj/effect/spawner/bundle/f13/armor/combat/mk2/dark,
done

2021-08-16 02:32 UTC, Mannybrado commented on code/_globalvars/lists/maintenance_loot.dm
>  	/obj/item/clothing/head/helmet/f13/combat/mk2,
done

2021-08-16 02:32 UTC, Mannybrado commented on code/modules/fallout/misc/gangs.dm
>  		/datum/gang_item/weapon/type93,
done

2021-08-16 02:42 UTC, Looreydev approved these changes

2021-08-20 05:18 UTC, Mannybrado commented
man. fuck it.

2021-08-20 05:18 UTC, closed without merging