improves raider outlaw loadouts a bit and adds a few new ones
FortunaSS13/Fortuna pull request #393
Opened 2021-10-24 15:05 UTC by chemistrymain3

adds  a couple new outlaw loadouts

improves a bunch of other outlaw loadouts, scaling their power up considerably (but not stupidly, hopefully)

removes the skillbook picking thing, instead skillbooks come with the outlaw.

all of these are up for review tbh

anyway this also coincidentally buffs the autopipe rifle a bit

if it's too strong i'll nerf it

this was requested by a mob of screamig ppl on discord

## Why It's Good For The Game

current outlaw loadouts are piss awful

the new ones should be more manageable, tbh. nobody has guns that are much stronger than like, magneto wattzes or so forth. some of these loadouts are stronger than others but yah

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: improves outlaw loadouts a bit
tweak: buffs the autopipe rifl a lil
add: some new outlaw loadouts
/:cl:

2021-10-29 23:46 UTC, zuliouse approved these changes

2021-10-29 23:52 UTC, zuliouse requested changes

2021-10-29 23:52 UTC, zuliouse commented on code/modules/jobs/job_types/wasteland.dm
> +		/obj/item/reagent_containers/syringe/medx = 1,
/obj/item/reagent_containers/inhaler/jet
/obj/item/reagent_containers/hypospray/medipen/medx

2021-10-29 23:54 UTC, zuliouse commented on code/modules/jobs/job_types/wasteland.dm
> +		/obj/item/reagent_containers/pill/patch/jet = 3,
/obj/item/reagent_containers/inhaler/jet

2021-10-30 00:11 UTC, AdamElTablawy commented on code/modules/jobs/job_types/wasteland.dm
> +		/obj/item/reagent_containers/pill/patch/jet = 3,
resolve

2021-10-30 00:11 UTC, AdamElTablawy commented on code/modules/jobs/job_types/wasteland.dm
> +		/obj/item/reagent_containers/syringe/medx = 1,
resolve

2021-10-31 12:02 UTC, Pebblesthe2nd commented
Stumbled on this PR and saw its using assets from the light/medium/heavy armor rework that I was doing pre-great revolution. Its not really meant to coexist with the old system, and will create some issues with redundancies down the line. 

Unless you're adopting and finishing the system it might be advisable to just untick it or delete it all together, instead of modifying individual items to fit with linearmor again. This item is the one I refer to:
/obj/item/clothing/suit/armored/light/duster/desperado

2021-11-01 00:12 UTC, AdamElTablawy commented
> Stumbled on this PR and saw its using assets from the light/medium/heavy armor rework that I was doing pre-great revolution. Its not really meant to coexist with the old system, and will create some issues with redundancies down the line.
> 
> Unless you're adopting and finishing the system it might be advisable to just untick it or delete it all together, instead of modifying individual items to fit with linearmor again. This item is the one I refer to: /obj/item/clothing/suit/armored/light/duster/desperado

We're finishing the system ourself, yeah.

2021-11-09 20:39 UTC, zuliouse approved these changes

2021-11-09 20:41 UTC, merged