Adjusting Raider Ghost Role
FortunaSS13/Fortuna pull request #399
Opened 2021-10-26 20:32 UTC by Tron-117

I'm seeing the value in adding the raider ghost role as a sort of antag to spice things up. I must see how players interact with this role to know how to move forward with it.

## About The Pull Request
Will be doing some experiments in the coming days to see how players use the roles/react to them.
Also changed some of the damage coefficient on the priest CoR mobs. I decided to put it in this PR as it's not really a big change.

## Why It's Good For The Game
Ghost roles may actually bring some value to the game, might as well make them somewhat wortwhile.

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: Added two extra grease gun mags, two stims, and a headset to the raider ghost role
tweak: changes some of the damage coefficient values on two CoR mobs
tweak: Adds a couple traits to a halloween event species
/:cl:

2021-10-31 18:25 UTC, zuliouse reviewed
Conflicts with https://github.com/FortunaSS13/Fortuna/pull/413

2021-11-03 22:54 UTC, buffyuwu commented
let me know when you'd like a review

2021-11-07 20:41 UTC, Tron-117 commented
> let me know when you'd like a review

Review please (I could've sworn there was a request review button on this page)

2021-11-07 21:26 UTC, buffyuwu requested changes

2021-11-07 21:26 UTC, buffyuwu commented on code/game/objects/structures/ghost_role_spawners.dm
> +		/obj/item/ammo_box/magazine/greasegun = 4,
we will want this to remain 2 to match the other ghost roles
```suggestion
		/obj/item/ammo_box/magazine/greasegun = 2,
```

2021-11-10 03:31 UTC, buffyuwu approved these changes

2021-11-10 03:31 UTC, merged