adds fermichem stimpaks
FortunaSS13/Fortuna pull request #400
Opened 2021-10-27 01:39 UTC by chemistrymain3

so a list of changes

1. you can craft stimpaks now through chemistry via mixing blood and spaceacilln at a temperature between 500 and 550 and if you go over that you get (problems)

the stimpak reaction will yield stimpak fluid at relatively high rates but quickly decrease the temperature of the reaction, requiring constant monitoring

honestly the pH window is so lenient as to be nonexistent, and i might  tighten that up to give more room for error

there's also imitation stimpak fluid, obtained either through no effort whatsoever in chemistry OR just regular chemistry-it is less effective than proper stimpak fluid, but more effective than healing powder (i may tweak its numbers some).

to clarify everyone still spawns with real stims, but you either need chemistry to make more real stims, or you loot them. in the interim, you craft basic bitch improvised stimpaks instead.

also it turned out bitter drink was actually stronger than fucking super stims so i toned that down some. hopefully that addresses the fact that the legion actually get BETTER healing than anyone else in the game. i may tweak this further, honestly, because it doesn't seem like any other chem cares if you have bitter drink in your system and you can stack it, but whatever.

there were leftover reagents in stimpaks, which ir emoved (they were code bloat, they did not appear anyway.)

fucking up the proper chem stimpak reaction yields impure stimpak reagent and something else, so...don't fuck it up.

final change, corn no longer tastes like slime

## Why It's Good For The Game

honestly i dunno maybe some more use for chemistry that's not making bicaridine/salicylic stimpaks and reduces loresmash of people producing real functional pre-war stimpaks out of nowhere with no chemistry knowledge

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added imitation stimpaks, craftable or makeable through chemistry.
add: Added making stimpaks through chemistry. Don't fuck up.
balance: Bitter drink heals less than super stimpaks, now.
fix: Corn no longer tastes like slime.
/:cl:

2021-11-03 22:14 UTC, buffyuwu requested changes

2021-11-03 22:14 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpak/on_mob_life(mob/living/carbon/M)
yeah probably make this a subtype of /imitation, no?

2021-11-04 04:05 UTC, AdamElTablawy commented
fixed it

2021-11-07 09:31 UTC, buffyuwu approved these changes

2021-11-07 16:43 UTC, merged