Gun Loot/Dungeon Overhaul
FortunaSS13/Fortuna pull request #422
Opened 2021-11-07 00:55 UTC by zuliouse

## About The Pull Request

Reorganizes and rebalances the gun spawner tiers, adjusts the way mob spawn pits are configured and adjusts dungeons. Eliminates a few metagamey tactics for looting. Shifts the Church up from the bottom of the map and places it just south of Oasis, with a new layout. Also a number of relatively minor changes to the sewers.

## Why It's Good For The Game

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
balance: Rebalanced gun loot tiers/spawns and enemies within bunkers.
tweak: Made a number of adjustments to the map, too many to list in a changelog.
/:cl:

2021-11-07 02:43 UTC, TripleShades commented
Is the removal of unbreakable rock around the Den on purpose?

2021-11-07 03:21 UTC, zuliouse commented
> 
> 
> Is the removal of unbreakable rock around the Den on purpose?

Yes! My reasoning is that since the Den is already protected by a layer of reinforced walls and a lot of rock, there isn't any strong reason (in my opinion) that it should be completely impenetrable. I'd like to cut down on faction bases being impenetrable like that in general, but this was just a small change I made while I was adjusting the sewers. In the future I'd like to remove the scattered dense rock that's around the Legion and Oasis base too, since it doesn't really serve much purpose.

2021-11-07 21:47 UTC, buffyuwu commented
i reported the issue with the mapdiffrenders bot on their repo, in the meantime we'll be re-running the job if it runtimes

2021-11-10 21:28 UTC, buffyuwu commented on code/datums/components/crafting/recipes/recipes_medicine.dm
> -/datum/crafting_recipe/improvisedstimpak
hey did you mean to delete all this improvised stimpak stuff

2021-11-10 21:33 UTC, buffyuwu requested changes

2021-11-10 21:33 UTC, buffyuwu commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +/*/datum/chemical_reaction/stimpak
isnt this used in that uhhh improvised stim PR where they use a reagent again?

2021-11-10 21:33 UTC, buffyuwu commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	list_reagents = list(/datum/reagent/medicine/stimpak = 10, /datum/reagent/medicine/stimulants = 10, /datum/reagent/medicine/omnizine = 10)
i think that aforementioned PR also removes omnizine.. probably be rid of this file's changes wholesale since they undo a lot of their work

2021-11-10 22:07 UTC, buffyuwu approved these changes
tentatively approving this but if there's changes this undoes in a pr merged previously i'll have to revert this and ask you re-do it!! hoping the hypospray stuff was a lone instance of that!!!

2021-11-10 22:08 UTC, merged