BoS feedback tweaks
FortunaSS13/Fortuna pull request #93
Opened 2021-09-01 16:13 UTC by Leudoberct1

## About The Pull Request

Adds a bunch of feedback changes to the BoS bunker. Shrinks the space used between the head knight office and firing range, fixes some issues with water tiles in the hydro bay, adds warning signs to the elevator, adds the payroll safe back in, fixes a vending machine, moves the bunker entrance to be further north in the sewers, rather than very close to the Den. Adds some dense rock (still passable) to try and encourage BoS not to mine all the way to their own entrance.

## Why It's Good For The Game

General QoL changes to make it better to play in the bunker, moving the entrance because people didn't like being so close to the Den due to frequent IC hostilities, generally just makes it more enjoyable to play in.

## Pre-Merge Checklist
- [X] Your Pull Request contains no breaking changes
- [X] You tested your changes locally, and they work.
- [X] There are no new Runtimes that appear.
- [X] You documented all of your changes.

## Changelog
:cl:
tweak: relocates the bos bunker entrance, moves and adds a few things around the bunker
add: re-adds the payroll safe, some warning signs etc around the bunker
/:cl:

2021-09-01 16:19 UTC, Looreydev requested changes

2021-09-01 16:19 UTC, Looreydev commented on _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
> +	barefootstep = "water;
```suggestion
	barefootstep = "water";
```

2021-09-01 16:19 UTC, Looreydev commented on _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
> +	barefootstep = "water;
```suggestion
	barefootstep = "water";
```

2021-09-01 16:19 UTC, Looreydev commented on _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
> +	barefootstep = "water;
```suggestion
	barefootstep = "water";
```

2021-09-01 16:19 UTC, Looreydev commented on _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
> +	barefootstep = "water;
```suggestion
	barefootstep = "water";
```

2021-09-01 20:14 UTC, merged

2021-09-05 08:28 UTC, ThyBaron commented
Hello! Were the marble bust's truly necessary?